import type { INodeProperties } from 'n8n-workflow';
import { exportArtifactsDescription } from './artifacts';
import { exportCreateDescription } from './create';
import { exportDownloadDescription } from './download';
import { exportListDescription } from './list';
import { exportOptionsDescription } from './options';
import { exportStatusDescription } from './status';

const showOnlyForExports = {
	resource: ['export'],
};

export const exportDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: showOnlyForExports,
		},
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create an export',
				description: 'Create an export job for a project',
				routing: {
					request: {
						method: 'POST',
						url: '=/projects/{{$parameter.projectId}}/exports',
					},
				},
			},
			{
				name: 'Download',
				value: 'download',
				action: 'Download an export artifact',
				description: 'Download a single export artifact by object key',
				routing: {
					request: {
						method: 'GET',
						url: '=/projects/{{$parameter.projectId}}/exports/download',
						encoding: 'arraybuffer',
						returnFullResponse: true,
					},
					output: {
						postReceive: [
							{
								type: 'binaryData',
								properties: {
									destinationProperty: '={{$parameter.binaryPropertyName}}',
								},
							},
						],
					},
				},
			},
			{
				name: 'Get Status',
				value: 'get',
				action: 'Get export status',
				description: 'Get the status of an export job',
				routing: {
					request: {
						method: 'GET',
						url: '=/projects/{{$parameter.projectId}}/exports/{{$parameter.exportId}}',
					},
				},
			},
			{
				name: 'List',
				value: 'list',
				action: 'List exports',
				description: 'List exports for a project',
				routing: {
					request: {
						method: 'GET',
						url: '=/projects/{{$parameter.projectId}}/exports',
					},
					output: {
						postReceive: [
							{
								type: 'rootProperty',
								properties: {
									property: 'exports',
								},
							},
						],
					},
				},
			},
			{
				name: 'List Artifacts',
				value: 'artifacts',
				action: 'List export artifacts',
				description: 'List artifacts generated by an export job',
				routing: {
					request: {
						method: 'GET',
						url: '=/projects/{{$parameter.projectId}}/exports/{{$parameter.exportId}}/artifacts',
					},
					output: {
						postReceive: [
							{
								type: 'rootProperty',
								properties: {
									property: 'artifacts',
								},
							},
						],
					},
				},
			},
			{
				name: 'Options',
				value: 'options',
				action: 'Get export options',
				description: 'Get available locales, themes, and content variables',
				routing: {
					request: {
						method: 'GET',
						url: '=/projects/{{$parameter.projectId}}/exports/options',
					},
				},
			},
		],
		default: 'create',
	},
	...exportCreateDescription,
	...exportStatusDescription,
	...exportListDescription,
	...exportArtifactsDescription,
	...exportOptionsDescription,
	...exportDownloadDescription,
];
